import { NextApiRequest, NextApiResponse } from 'next';

const formFields = {
  insurances: {
    123: { id: 123, name: 'workersCompensation', groups: [1, 2, 3, 4] },
    456: { id: 456, name: 'cyberInsurance', groups: [1] },
    789: { id: 789, name: 'farmInsurance', groups: [2] },
  },
  groups: {
    1: {
      id: 1,
      group: 'personalInfo',
      title: 'Who is the primary contact for this policy?',
      description:
        'This person will receive all communications from Newfront about this policy.' +
        'You can change this contact information later. If you’re not sure, just add' +
        'your contact information.',
      fields: [1, 2, 3],
    },
    2: { id: 2, group: 'company', title: 'Tell us about your company', fields: [4, 5, 6, 7, 8] },
    3: { id: 3, group: 'employees', title: 'Tell us about your employees', fields: [9, 10, 11] },
    4: { id: 4, group: 'payment', title: 'How do you want to pay for your policy?', fields: [12] },
  },
  fields: {
    1: {
      id: 1,
      value: '',
      visible: true,
      label: 'Full Name',
      fieldId: 'fullname',
      error: 'please enter a valid name',
      description: 'your full name',
      type: 'text',
      required: true,
    },
    2: {
      id: 2,
      value: '',
      visible: true,
      label: 'Role',
      fieldId: 'role',
      error: 'please enter a role',
      description: 'your role',
      type: 'text',
      required: true,
    },
    3: {
      id: 3,
      value: '',
      visible: true,
      label: 'Phone number',
      fieldId: 'phone',
      error: 'please enter a valid phone',
      description: 'your phone',
      type: 'text',
      required: false,
    },
    4: {
      id: 4,
      value: '',
      visible: true,
      label: 'Company Name',
      fieldId: 'companyName',
      error: 'please enter a company name',
      description: 'your company name',
      type: 'text',
      required: false,
    },
    5: {
      id: 5,
      value: '',
      visible: true,
      label: 'What is your Federal Employer Identification Number? (FEIN)',
      fieldId: 'fein',
      error: 'please enter a valid FEIN',
      description: 'your FEIN',
      type: 'text',
      required: true,
    },
    6: {
      id: 6,
      value: '',
      visible: true,
      label: 'Years in bussiness',
      fieldId: 'yearsBusiness',
      error: 'please enter a valid number',
      description: 'your years',
      type: 'number',
      required: false,
    },
    7: {
      id: 7,
      value: '',
      visible: true,
      label: 'Number of locations',
      fieldId: 'locations',
      error: 'please enter locations',
      description: 'your number of locations',
      type: 'number',
      required: false,
    },
    8: {
      id: 8,
      value: '',
      visible: true,
      label: 'In which states do you operate?',
      fieldId: 'states',
      error: 'please enter states',
      description: 'states',
      type: 'text',
      required: false,
    },
    9: {
      id: 9,
      value: '',
      visible: true,
      label: 'What’s the name of the clinic, physician, or ER used for work injuries?',
      fieldId: 'clinicName',
      error: 'please enter clinic',
      description: 'clinic',
      type: 'text',
      required: false,
    },
    10: {
      id: 10,
      value: {
        1: { id: 1, checked: false },
        2: { id: 2, checked: false },
        3: { id: 3, checked: false },
      },
      visible: true,
      label: 'questions',
      fieldId: 'questions',
      error: 'please select one',
      description: 'different questions',
      type: 'multipleSelection',
      required: false,
      options: [
        { id: 1, label: 'Do you provide group medical insurance?' },
        { id: 2, label: 'Do you offer a retirement or pension plan?' },
        { id: 3, label: 'Do you give paid vacation?' },
      ],
      child: 11,
    },
    11: {
      id: 11,
      value: '',
      visible: false,
      label: 'Please provide details about the paid vacation',
      fieldId: 'vacation',
      error: 'please enter value',
      description: 'vacations info',
      type: 'text',
      required: true,
      parent: 10,
    },
    12: {
      id: 12,
      type: 'singleSelection',
      fieldId: 'insuranceType',
      value: '',
      options: [
        {
          id: 1,
          label: 'I want to pay Newfront',
          description: 'You’ll pay Newfront instead of paying each insurance company separately. There are no fees.',
          tag: 'Recommended',
        },
        {
          id: 2,
          label: 'I want to pay the insurance company directly',
          description:
            'You’ll receive bills from the insurance company and it will be your responsibility to make sure they are paid to keep your coverage.',
          tag: null,
        },
      ],
    },
  },
};

export default async function dataset(req: NextApiRequest, res: NextApiResponse): Promise<void> {
  return res.status(200).json(formFields);
}
